server: 
  port : 8080
#  servlet:
#    context-path : /sunjet

spring:
#  mvc:
#    static-path-pattern : /resources/**
#    view:
#      prefix : /WEB-INF/views/
#      suffix : .jsp
      
  thymeleaf:
    cache : false
    encoding : UTF-8
    mode : HTML5
    suffix : .html
    prefix : classpath:/templates/
  resources:
    static-locations : classpath:/static/
    
scheduler:
  trigger: 
    calendarJob: 
      cron: 0 0 1 1 1 ?    