server: 
  port : 8078
#  servlet:
#    context-path : /sunjet


app:
  jwtSecret: bezKoderSecretKey
  jwtExpirationMs: 86400000
    
scheduler:
  trigger: 
    calendarJob: 
      cron: 0 0 1 1 1 ?    