#spring:
#  dsopen:
#    jndi-name: java:/OracleDS
    
log:
  basic:
    path: log/sunjet-front
    
server: 
  port : 8078
  servlet:
    context-path : /sunjet


app:
  jwtSecret: bezKoderSecretKey
  jwtExpirationMs: 600000000
    
scheduler:
  trigger: 
    calendarJob: 
      cron: 0 0 1 1 1 ?        
      
#logging:
#  file: logs/application-debug.log
#  pattern:
#    console: "%d{yyyy/MM/dd HH:mm:ss.SSS} [%thread] [%logger:%line] : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"
#  level:
#    root: info
#    org.springframework.web: ERROR
#    com.sunjet: DEBUG
 

    